version: '3'
services:
  zookeeper:
    build: ./zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"

  storm-ui:
    build: ./storm-ui
    container_name: storm-ui
    depends_on:
      - zookeeper
      - storm-nimbus
    links:
      - zookeeper
      - storm-nimbus
    restart: always
    ports:
      - "8080:8080"

  storm-nimbus:
    build: ./storm-nimbus
    container_name: storm-nimbus
    depends_on:
      - zookeeper
    links:
      - zookeeper
    restart: always
    ports:
      - "6627:6627"
    volumes:
      - ./storm-nimbus/storm:/code-storm
      - ./storm-nimbus/storm-starter:/code-storm-starter

  storm-supervisor:
    build: ./storm-supervisor

    depends_on:
      - storm-nimbus
      - zookeeper
    links:
      - storm-nimbus
      - zookeeper
    restart: always
