version: '3'
services:
  dashboard:
    build: ./dashboard
    ports:
      - "8050:8050"
    volumes:
     - ./dashboard:/code
    depends_on:
       - rabbitmq
       - zookeeper
    restart: always

  receiver_debug:
    build: ./receiver_debug
    volumes:
     - ./receiver_debug:/code
    depends_on:
       - rabbitmq
       - api
       - zookeeper
       - storm-nimbus
    restart: always
    
  generator:
    build: ./generator
    volumes:
     - ./generator:/code
    depends_on:
       - rabbitmq
       - api
       - zookeeper
       - storm-nimbus
    restart: always

  rabbitmq:
    build: ./rabbitmq
    ports:
      - "5672:5672"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  mongo_client:
    build: ./mongo_client
    volumes:
    - ./mongo_client:/code
    restart: always
    depends_on:
    - rabbitmq

  mongo:
    build: ./mongo
    ports:
     - "27017:27017"
    logging:
     driver: none

  api:
    build: ./api
    depends_on:
      - rabbitmq
    ports:
      - "3000:3000"
    restart: always

  zookeeper:
    build: ./zookeeper
    container_name: zookeeper
    depends_on:
      - rabbitmq
    restart: always
    ports:
      - "2181:2181"
  storm-ui:
    build: ./storm-ui
    container_name: storm-ui
    depends_on:
      - zookeeper
      - storm-nimbus
      - rabbitmq
    ports:
      - "8080:8080"
    restart: always
  storm-nimbus:
    build: ./storm-nimbus
    container_name: storm-nimbus
    depends_on:
      - zookeeper
      - rabbitmq
    ports:
      - "6627:6627"
    restart: always
  storm-submit:
    build: ./storm-submit
    container_name: storm-submit
    depends_on:
      - zookeeper
      - rabbitmq
      - storm-nimbus
    volumes:
      - ./storm-submit/topology-jar:/topology-jar
    restart: on-failure
  storm-supervisor:
    build: ./storm-supervisor
    depends_on:
      - storm-nimbus
      - zookeeper
      - rabbitmq
    restart: always
