version: '3'
services:
  generator:
    build: ./generator
    volumes:
     - ./generator:/code
  rabbitmq:
    build: ./rabbitmq
    ports:
      - "5672:5672"
  api:
    build: ./api
  receiver_debug:
    build: ./receiver_debug
    volumes:
     - ./receiver_debug:/code
